name: xdo
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.4
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.10
  - fontconfig=2.13.0
  - freetype=2.10.4
  - glib=2.66.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - notebook=6.1.6
  - numpy-base=1.19.2
  - openssl=1.1.1i
  - packaging=20.8
  - pandas=1.1.5
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.3.3
  - prometheus_client=0.9.0
  - prompt_toolkit=3.0.8
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.7.4
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.6.12
  - python-dateutil=2.8.1
  - pytz=2020.5
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.0
  - send2trash=1.5.0
  - setuptools=51.3.3
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - pip:
code      - absl-py==0.10.0
      - astunparse==1.6.3
      - attrs==19.3.0
      - cachetools==4.2.0
      - chardet==4.0.0
      - chex==0.0.3
      - cloudpickle==1.6.0
      - cvxopt==1.2.5
      - cycler==0.10.0
      - dataclasses==0.7
      - dm-haiku==0.0.3
      - dm-tree==0.1.5
      - flatbuffers==1.12
      - future==0.18.2
      - gast==0.3.3
      - google-auth==1.24.0
      - google-auth-oauthlib==0.4.2
      - google-pasta==0.2.0
      - grpcio==1.32.0
      - h5py==2.10.0
      - hypothesis==5.38.0
      - idna==2.10
      - ipython==5.8.0
      - jax==0.2.7
      - jaxlib==0.1.57
      - keras-preprocessing==1.1.2
      - kiwisolver==1.3.1
      - markdown==3.3.3
      - matplotlib==3.2.2
      - mock==4.0.2
      - nashpy==0.0.19
      - networkx==2.4
      - numpy==1.19.5
      - oauthlib==3.1.0
      - opt-einsum==3.3.0
      - optax==0.0.2
      - prompt-toolkit==1.0.18
      - protobuf==3.14.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - requests==2.25.1
      - requests-oauthlib==1.3.0
      - rsa==4.7
      - scipy==1.4.1
      - simplegeneric==0.8.1
      - sortedcontainers==2.3.0
      - tensorboard==2.4.1
      - tensorboard-plugin-wit==1.8.0
      - tensorflow==2.4.0
      - tensorflow-estimator==2.4.0
      - tensorflow-probability==0.7.0
      - termcolor==1.1.0
      - toolz==0.11.1
      - torch==1.7.0
      - typing-extensions==3.7.4.3
      - urllib3==1.26.2
      - werkzeug==1.0.1
      - wrapt==1.12.1
